# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [9]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)

random_tensor.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [63]:
# Create another random tensor
oneBySevenTensor = torch.rand(1,7)

print(f"Original size 1x7 : {oneBySevenTensor.shape}")

# Perform matrix multiplication 

oneBySevenTensorTransposed = torch.transpose(oneBySevenTensor, 0 , 1)

print(f"Transposed size 7x1 : {oneBySevenTensorTransposed.shape}")

mm = torch.mm(random_tensor, oneBySevenTensorTransposed)


print(f"matrix multiplication: {mm}")

Original size 1x7 : torch.Size([1, 7])
Transposed size 7x1 : torch.Size([7, 1])
matrix multiplication: tensor([[1.7519],
        [2.1807],
        [1.3384],
        [1.9460],
        [1.5817],
        [1.9300],
        [2.0969]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [74]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor = torch.rand(7, 7)
random_tensor2 = torch.rand(7,1)

# Matrix multiply tensors
torch.mm(random_tensor,random_tensor2)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [123]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234) #Equivelent for CUDA

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [200]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(f"Is cuda available? : {torch.cuda.is_available()}")
if(torch.cuda.is_available()):
    torch.set_default_device('cuda')

    print(f"Default device: {torch.get_default_device()}\n")

else:
    print("Cuda not available!! \n\n")

        
# Create two random tensors on GPU
rand_tensor_1 = torch.rand(2,3)
rand_tensor_2 = torch.rand(2,3)

print(f"{rand_tensor_1} \n\n {rand_tensor_2}")

Is cuda available? : True
Default device: cuda:0

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') 

 tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [204]:
# Perform matmul on tensor_A and tensor_B
matmul = torch.matmul(rand_tensor_1, rand_tensor_1.transpose(1,0))

matmul

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [210]:
# Find max
maxValue = matmul.max()

# Find min
minValue = matmul.min()

maxValue, minValue

(tensor(1.4578, device='cuda:0'), tensor(0.8358, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [214]:
# Find arg max
maxValueIndex = matmul.argmax()

# Find arg min
minValueIndex = matmul.argmin()

maxValueIndex, minValueIndex

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [224]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
squeezedTensor = torch.squeeze(tensor)

# Print out tensors and their shapes
tensor, tensor.shape , squeezedTensor, squeezedTensor.shape


(tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
            0.6333, 0.5733]]]], device='cuda:0'),
 torch.Size([1, 1, 1, 10]),
 tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
         0.5733], device='cuda:0'),
 torch.Size([10]))